"""
Annotated Config Generator
Produces the final .sh file with inline [NEW], [CHANGED], [FILL IN] annotations.
"""
from __future__ import annotations
import re
from datetime import datetime, timezone
from .parser import ShellVariable, PLACEHOLDER
from .differ import DiffResult


def _quote(value: str) -> str:
    """Return a safely-quoted shell value."""
    # Use single quotes if the value contains special chars, else double
    if re.search(r'''[`$"\\!]''', value):
        return f"'{value}'"
    return f'"{value}"'


def generate_new_tenant(
    file_name: str,
    new_vars: list[ShellVariable],
    stage: str = "",
) -> str:
    """All variables are new — annotate placeholders only."""
    lines = _header(file_name, "new", stage)

    for v in new_vars:
        if v.comment:
            lines.append(f"# {v.comment}")
        if v.needs_input:
            lines.append("# [FILL IN REQUIRED]")
        lines.append(f"export {v.name}={_quote(v.value)}")
        lines.append("")

    return "\n".join(lines)


def generate_existing_tenant(
    file_name: str,
    diff_result: DiffResult,
    old_vars: list[ShellVariable],
    new_vars: list[ShellVariable],
    stage: str = "",
) -> str:
    """
    Walk the new variable order, annotating new/changed vars.
    Unchanged vars keep their existing values.
    Removed vars are excluded but listed in a trailing comment block.
    """
    old_map   = {v.name: v for v in old_vars}
    changed_map = {v.name: old_val for v, old_val in diff_result.changed}

    lines = _header(file_name, "existing", stage)

    for v in new_vars:
        if v.comment:
            lines.append(f"# {v.comment}")

        if v.name not in old_map:
            # Brand-new variable in this release
            lines.append("# [NEW - ACTION REQUIRED]")
            if v.needs_input:
                lines.append("# [FILL IN REQUIRED]")
            lines.append(f"export {v.name}={_quote(v.value)}")

        elif v.name in changed_map:
            # Value changed in this release
            lines.append(f"# [CHANGED - was: {changed_map[v.name]}]")
            lines.append(f"export {v.name}={_quote(v.value)}")

        else:
            # Unchanged — preserve existing value
            existing_value = old_map[v.name].value
            lines.append(f"export {v.name}={_quote(existing_value)}")

        lines.append("")

    # Trailing note about removed variables
    if diff_result.removed:
        lines.append("# ─────────────────────────────────────────────")
        lines.append("# REMOVED IN THIS RELEASE — delete from your config:")
        for r in diff_result.removed:
            lines.append(f"#   {r.name}={_quote(r.value)}")
        lines.append("# ─────────────────────────────────────────────")

    return "\n".join(lines)


def _header(file_name: str, tenant_type: str, stage: str) -> list[str]:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        "#!/bin/bash",
        f"# {file_name}",
        f"# Generated by Config Generator v1 — {ts}",
        f"# Tenant type: {tenant_type}",
    ]
    if stage:
        lines.append(f"# Stage: {stage}")
    lines.append("")
    return lines
